### ISSUE TITLE
A handle on my bundled PRs

### ISSUE THREAD

**Issue by apehex** [pfalcon/awesome-smarthome#8]
Hello @pfalcon 
I made a bulk submission a while ago and got lazy afterwards.

So here are my proposals, sorted in separate PRs.
It covers cosmetics, awesome "compliance", linting, etc.
Some are obviously opiniated, but it should now be easy to edit that out.

Btw sorry about the licence issue, I put the one [recommended by the creator of the project](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) thoughtlessly, it was out of line.

cheers!

**Comment by apehex** [comment]
I'd suggest merging in this order:

1) independent / harmless commits:
add-a-table-of-contents
add-awesome-badge
add-contribution-guidelines
display-stars-and-languages-with-shields
prettify-the-intro
link-to-related-resources

2) opinionated commits:
move-the-closed-source-in-a-separate-file
remove-the-dead-projects

3) the one that will need the most editing:
make-the-format-and-texts-uniform

**Comment by apehex** [comment]
I have other suggestions:
- sorting alphabetically
- adding descriptions
- organizing the sections by topics rather than open-source vs commercial

but it will be way easier once this is -hopefully- digested

**Comment by apehex** [comment]
I know this may look like petty PRs but I think it may help / motivate people to contribute here rather than create an altogether new list...

**Comment by apehex** [comment]
you can preview the overall result here:
https://github.com/moodule/awesome-smarthome/tree/master

**Comment by pfalcon** [comment]
Just a quick comment that I appreciate giving this another try.

> I know this may look like petty PRs but I think it may help / motivate people to contribute here rather than create an altogether new list...

Attention to detail is very important trait of good open-source projects, and again, I appreciate yours. But there's indeed a fine and definitely subjective line between "attentive to detail" and "petty" indeed. 

I guess as a prelude, it would make sense to disclose how this list came to existence in the first place. I maintained a list of smarthome-related projects in a libreoffice spreadsheet for a couple of years, to see what are active and would be worth my attention somewhere in the future, when I build up "my IoT fleet". And I'm a developer, not just a user, so that's my focus (which software more worthy to be hacked on, not just used).

So, maintaining that for a couple of years and seeing no other clear "awesome" list of related stuff, I thought: "well, why I don't make my list public, and cater it a bit (sic!) for end users, and promote "my agenda" ". And my agenda is very simple: I'm an open-source developer, so I'm interesting in promoting open-source software, and warn potential users of dangers of proprietary solutions, especially in such subtle area as your own home.

Hopefully that makes clear: a) the list is intended to be first of all interested to myself, I'm not interested to twist it to cater to somebody with completely different outlook at the expense of my maintenance time; b) I have my ideas on how to structure/maintain it; c) the areas which may seem as "not given enough attention" may be deliberately so, as I simply don't find it giving enough usefulness/time used to maintain it ratio.

So, I apologize in advance if I won't be able to take all of your contributions. I definitely will comment on each proposal as time permits. If you won't be happy with the decisions, you're surely welcome to maintain your list. But if you base your list on my, please be sure to give me credit and release it on the compatible license (as this list is not public domain, for very obvious reason - public domain promotes plagiarism).

**Comment by pfalcon** [comment]
> sorting alphabetically

Instead of sorting by number of stars? That doesn't fly with me, sorry. Both me-as-a-user, and me-as-a-developer wants to know immediately which projects are the most popular. As a user, because such would likely have the most featurex and widest support, as a developer, because contributing to popular projects would likely have the best impact (for both myself and other users). And I assume that majority of readers would be interested in very this kind of info.

**Comment by apehex** [comment]
I submit here especially to try and improve on what's already existing, because:
- I'm fed up of seeing everyone do it's own project in his corner
- people coding on their own produce low quality software and curation

So when I say this is petty I mean the result is just a list, nothing is built on it.
Still I know I felt like doing my own after seeing yours, and this is a waste of effort on BOTH sides!
(well the 3 sides: you, me and the readers)

**Comment by apehex** [comment]
If you want to promote OS whyyyyyy list commercial crap?
It's not curation, everyone knows about google home honestly...

**Comment by apehex** [comment]
Also: as a software developer you might understand the value of clean, structured and consistent conventions. For efficiency.
That's also what the awesome project is about: promoting the best, in a no BS style.
And you borrow the banner, it gives you visibilty sooooo may-be we can show that we're grateful by following their guidelines, idk?

**Comment by apehex** [comment]
If everything is meant to be open, why dwell on the "OS vs commercial"?
I'd propose to order by topic, and the first one would be sthg like "Central Hub".

**Comment by apehex** [comment]
I understand that I might touch a nerve, but after 2 years may-be you want to remove the rant about closed solutions and spying? 
¯\\\_(ツ)\_/¯

**Comment by apehex** [comment]
Anyway thanks for reviewing this!
Like you I wanted to publish my research on the topic f-a-s-t, have it available and forget about it.
As I do for every new topic I delve in: start by digesting/contributing to the awesome lists.

**Comment by pfalcon** [comment]
To capture all the discussion, from https://github.com/pfalcon/awesome-smarthome/pull/9#issuecomment-589956769 :

> Again whyyyyy do you put commercial systems at all?

From https://github.com/pfalcon/awesome-smarthome/issues/8#issuecomment-589950411 :

> warn potential users of dangers of proprietary solutions, especially in such subtle area as your own home.

(Sorry, "dangers" was missing in the original comment.) Of course, I don't want to demonize commercial software (most of smarthome software will be such), so besides obvious failures, I try to include successful systems (which were well-supported for extended time) to provide balanced view.

**Comment by pfalcon** [comment]
> opinionated commits:
move-the-closed-source-in-a-separate-file
remove-the-dead-projects

So, to summarize, the "agenda" of this list is:

1. Raise awareness that (quite) a number of open-source smarthome solutions exist.
2. Raise awareness that using commercial systems has its drawbacks (the main being privacy/security/long-term sustainability).
3. Encourage participation/contribution in existing open-source projects, and discourage creation of even more fragmented solutions.

So, listing fail'ish commercial systems is imperative for the aim of the projects, then listing non-fail'ish commercial systems is required to provide balanced view.

Similarly, listing "dead" projects is imperative to address p.3, "discourage creation of even more fragmented solutions". Just imagine - someone spent a lot of effort, created a project which caught attention of a lot of people, and now that project is ... dead. Time to think thrice what you're going to spend your time, maybe you'll be creating another dead project? It worked well for me (just imagine, I didn't start coding my project, instead got off with writing list of others' projects), and I'm only happy to spread the epiphany.

(Oh, and it goes both ways - some people love "dead" projects. "Dead" projects may be "perfect" projects, whose authors stopped to rape the code of the project, so users may finally use it and adapt it for their needs, without fearing that some upcoming useless change will tear their work apart. ;-) )

**Comment by apehex** [comment]
wow so full of yourself.

thinking you "raise awareness" by saying google assistant trades data?? lol... we're on github EVERYONE here knows that.

this is not "awesome-smarthome" -you don't even try to follow the project- at best it's "pfalcons-limited-and-old-opinions-on-smarthome-he-thinks-are-so-good-they-should-stay-the-same-forever".

yep dead project it is, I leave you in your element, 0 care for that.

**Comment by pfalcon** [comment]
As I warned in the beginning, I have a good understanding why and how I do this thing. Not that it can't be influenced, but someone doing that would need to a) first understand the existing idea; b) provide even better/better expressed idea. That's hard ;-I.

> lol... we're on github EVERYONE here knows that.

Sure. Everyone knows everything. Many just forget a lot of that, so write down or read back.

> -you don't even try to follow the project-

You have a (mis)concenption that there's some dude who trademarked word "awesome" and bends everyone to stamp a picture of those sunglasses whenever they use it. That's not the case. For some people, "awesome list" means "list of things trying to inspire [different feelings] with this-or-that level of subjectivity and thoroughness". (For many other people, it means many other different things.)

If you wouldn't like the rest of PRs to be processed, please don't forget to close them.
